#ifndef _ROS_mower_msgs_Emergency_h
#define _ROS_mower_msgs_Emergency_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "ros/time.h"

namespace mower_msgs
{

  class Emergency : public ros::Msg
  {
    public:
      typedef ros::Time _stamp_type;
      _stamp_type stamp;
      typedef bool _active_emergency_type;
      _active_emergency_type active_emergency;
      typedef bool _latched_emergency_type;
      _latched_emergency_type latched_emergency;
      typedef const char* _reason_type;
      _reason_type reason;

    Emergency():
      stamp(),
      active_emergency(0),
      latched_emergency(0),
      reason("")
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      offset += this->stamp.serialize(outbuffer + offset);
      union {
        bool real;
        uint8_t base;
      } u_active_emergency;
      u_active_emergency.real = this->active_emergency;
      *(outbuffer + offset + 0) = (u_active_emergency.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->active_emergency);
      union {
        bool real;
        uint8_t base;
      } u_latched_emergency;
      u_latched_emergency.real = this->latched_emergency;
      *(outbuffer + offset + 0) = (u_latched_emergency.base >> (8 * 0)) & 0xFF;
      offset += sizeof(this->latched_emergency);
      uint32_t length_reason = strlen(this->reason);
      varToArr(outbuffer + offset, length_reason);
      offset += 4;
      memcpy(outbuffer + offset, this->reason, length_reason);
      offset += length_reason;
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      offset += this->stamp.deserialize(inbuffer + offset);
      union {
        bool real;
        uint8_t base;
      } u_active_emergency;
      u_active_emergency.base = 0;
      u_active_emergency.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->active_emergency = u_active_emergency.real;
      offset += sizeof(this->active_emergency);
      union {
        bool real;
        uint8_t base;
      } u_latched_emergency;
      u_latched_emergency.base = 0;
      u_latched_emergency.base |= ((uint8_t) (*(inbuffer + offset + 0))) << (8 * 0);
      this->latched_emergency = u_latched_emergency.real;
      offset += sizeof(this->latched_emergency);
      uint32_t length_reason;
      arrToVar(length_reason, (inbuffer + offset));
      offset += 4;
      for(unsigned int k= offset; k< offset+length_reason; ++k){
          inbuffer[k-1]=inbuffer[k];
      }
      inbuffer[offset+length_reason-1]=0;
      this->reason = (char *)(inbuffer + offset-1);
      offset += length_reason;
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/Emergency"; };
    virtual const char * getMD5() override { return "6dcfd299684b169865102369af95a2ce"; };

  };

}
#endif
