// Code generated by generate_go_msgs.sh — DO NOT EDIT.
package visualization

import (
	"github.com/cedbossneo/mowglinext/pkg/msgs/geometry"
)

// Duration matches builtin_interfaces/msg/Duration.
type Duration struct {
	Sec                       int32                          `json:"sec"`
	Nanosec                   uint32                         `json:"nanosec"`
}

// ColorRGBA matches std_msgs/msg/ColorRGBA.
type ColorRGBA struct {
	R                         float32                        `json:"r"`
	G                         float32                        `json:"g"`
	B                         float32                        `json:"b"`
	A                         float32                        `json:"a"`
}

// Marker matches visualization_msgs/msg/Marker.
type Marker struct {
	Header                    geometry.Header                `json:"header"`
	Ns                        string                         `json:"ns"`
	Id                        int32                          `json:"id"`
	Type                      int32                          `json:"type"`
	Action                    int32                          `json:"action"`
	Pose                      geometry.Pose                  `json:"pose"`
	Scale                     geometry.Vector3               `json:"scale"`
	Color                     ColorRGBA                      `json:"color"`
	Lifetime                  Duration                       `json:"lifetime"`
	Points                    []geometry.Point               `json:"points"`
}

// MarkerArray matches visualization_msgs/msg/MarkerArray.
type MarkerArray struct {
	Markers                   []Marker                       `json:"markers"`
}

