// Code generated by generate_go_msgs.sh — DO NOT EDIT.
package geometry

// Stamp matches builtin_interfaces/msg/Time.
type Stamp struct {
	Sec                       uint32                         `json:"sec"`
	Nanosec                   uint32                         `json:"nanosec"`
}

// Header matches std_msgs/msg/Header.
type Header struct {
	Stamp                     Stamp                          `json:"stamp"`
	FrameId                   string                         `json:"frame_id"`
}

// Point matches geometry_msgs/msg/Point.
type Point struct {
	X                         float64                        `json:"x"`
	Y                         float64                        `json:"y"`
	Z                         float64                        `json:"z"`
}

// Point32 matches geometry_msgs/msg/Point32.
type Point32 struct {
	X                         float32                        `json:"x"`
	Y                         float32                        `json:"y"`
	Z                         float32                        `json:"z"`
}

// Polygon matches geometry_msgs/msg/Polygon.
type Polygon struct {
	Points                    []Point32                      `json:"points"`
}

// Pose matches geometry_msgs/msg/Pose.
type Pose struct {
	Position                  Point                          `json:"position"`
	Orientation               Quaternion                     `json:"orientation"`
}

// PoseStamped matches geometry_msgs/msg/PoseStamped.
type PoseStamped struct {
	Header                    Header                         `json:"header"`
	Pose                      Pose                           `json:"pose"`
}

// PoseWithCovariance matches geometry_msgs/msg/PoseWithCovariance.
type PoseWithCovariance struct {
	Pose                      Pose                           `json:"pose"`
	Covariance                [36]float64                    `json:"covariance"`
}

// Quaternion matches geometry_msgs/msg/Quaternion.
type Quaternion struct {
	X                         float64                        `json:"x"`
	Y                         float64                        `json:"y"`
	Z                         float64                        `json:"z"`
	W                         float64                        `json:"w"`
}

// Twist matches geometry_msgs/msg/Twist.
type Twist struct {
	Linear                    Vector3                        `json:"linear"`
	Angular                   Vector3                        `json:"angular"`
}

// TwistStamped matches geometry_msgs/msg/TwistStamped.
type TwistStamped struct {
	Header                    Header                         `json:"header"`
	Twist                     Twist                          `json:"twist"`
}

// TwistWithCovariance matches geometry_msgs/msg/TwistWithCovariance.
type TwistWithCovariance struct {
	Twist                     Twist                          `json:"twist"`
	Covariance                [36]float64                    `json:"covariance"`
}

// Vector3 matches geometry_msgs/msg/Vector3.
type Vector3 struct {
	X                         float64                        `json:"x"`
	Y                         float64                        `json:"y"`
	Z                         float64                        `json:"z"`
}

