// Code generated by generate_ts_types.sh — DO NOT EDIT.
// Re-run: cd gui && ./generate_ts_types.sh
//
// Field names are snake_case to match the JSON from rosbridge.

export type Point32 = {
  x?: number;
  y?: number;
  z?: number;
};

export type Point = {
  x?: number;
  y?: number;
  z?: number;
};

export type Polygon = {
  points?: Point32[];
};

export type Pose = {
  position?: Point;
  orientation?: Quaternion;
};

export type PoseStamped = {
  pose?: Pose;
};

export type PoseWithCovariance = {
  pose?: Pose;
  covariance?: number[];
};

export type Quaternion = {
  x?: number;
  y?: number;
  z?: number;
  w?: number;
};

export type Twist = {
  linear?: Vector3;
  angular?: Vector3;
};

export type TwistWithCovariance = {
  twist?: Twist;
  covariance?: number[];
};

export type Vector3 = {
  x?: number;
  y?: number;
  z?: number;
};

export type ColorRGBA = {
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type Path = {
  poses?: PoseStamped[];
};

export type OccupancyGridInfo = {
  resolution?: number;
  width?: number;
  height?: number;
  origin?: Pose;
};

export type OccupancyGrid = {
  info?: OccupancyGridInfo;
  data?: number[];
};

export type Imu = {
  orientation?: Quaternion;
  orientation_covariance?: number[];
  angular_velocity?: Vector3;
  angular_velocity_covariance?: number[];
  linear_acceleration?: Vector3;
  linear_acceleration_covariance?: number[];
};

export type LaserScan = {
  angle_min?: number;
  angle_max?: number;
  angle_increment?: number;
  time_increment?: number;
  scan_time?: number;
  range_min?: number;
  range_max?: number;
  ranges?: number[];
  intensities?: number[];
};

export type MarkerArray = {
  markers?: Marker[];
};

export type Marker = {
  ns?: string;
  id?: number;
  type?: number;
  action?: number;
  pose?: Pose;
  scale?: Vector3;
  color?: ColorRGBA;
  lifetime?: number;
  frame_locked?: boolean;
  points?: Point[];
  colors?: ColorRGBA[];
  text?: string;
  mesh_resource?: string;
  mesh_use_embedded_materials?: boolean;
};

export const enum AbsolutePoseConstants {
  SOURCE_GPS = 1,
  SOURCE_LIGHTHOUSE = 2,
  SOURCE_SENSOR_FUSION = 100,
  FLAG_GPS_RTK = 1,
  FLAG_GPS_RTK_FIXED = 2,
  FLAG_GPS_RTK_FLOAT = 4,
  FLAG_GPS_DEAD_RECKONING = 8,
  FLAG_SENSOR_FUSION_RECENT_ABSOLUTE_POSE = 1,
  FLAG_SENSOR_FUSION_DEAD_RECKONING = 8,
};

export type AbsolutePose = {
  header?: { stamp: { sec: number; nanosec: number }; frame_id: string };
  sensor_stamp?: number;
  received_stamp?: number;
  source?: number;
  flags?: number;
  orientation_valid?: number;
  motion_vector_valid?: number;
  position_accuracy?: number;
  orientation_accuracy?: number;
  pose?: PoseWithCovariance;
  motion_vector?: Vector3;
  vehicle_heading?: number;
  motion_heading?: number;
};

export type CoveragePath = {
  is_outline?: boolean;
  path?: Path;
};

export type Emergency = {
  stamp?: { sec: number; nanosec: number };
  active_emergency?: boolean;
  latched_emergency?: boolean;
  lift_warning?: boolean;
  lift_duration_sec?: number;
  reason?: string;
};

export const enum ESCStatusConstants {
  ESC_STATUS_DISCONNECTED = 99,
  ESC_STATUS_ERROR = 100,
  ESC_STATUS_STALLED = 150,
  ESC_STATUS_OK = 200,
  ESC_STATUS_RUNNING = 201,
};

export type ESCStatus = {
  status?: number;
  current?: number;
  tacho?: number;
  rpm?: number;
  temperature_motor?: number;
  temperature_pcb?: number;
};

export const enum HighLevelStatusConstants {
  HIGH_LEVEL_STATE_NULL = 0,
  HIGH_LEVEL_STATE_IDLE = 1,
  HIGH_LEVEL_STATE_AUTONOMOUS = 2,
  HIGH_LEVEL_STATE_RECORDING = 3,
  HIGH_LEVEL_STATE_MANUAL_MOWING = 4,
};

export type HighLevelStatus = {
  state?: number;
  state_name?: string;
  sub_state_name?: string;
  current_area?: number;
  current_path?: number;
  current_path_index?: number;
  total_swaths?: number;
  completed_swaths?: number;
  skipped_swaths?: number;
  gps_quality_percent?: number;
  battery_percent?: number;
  is_charging?: boolean;
  emergency?: boolean;
};

export type ImuRaw = {
  dt?: number;
  ax?: number;
  ay?: number;
  az?: number;
  gx?: number;
  gy?: number;
  gz?: number;
  mx?: number;
  my?: number;
  mz?: number;
};

export type MapArea = {
  name?: string;
  area?: Polygon;
  obstacles?: Polygon[];
  is_navigation_area?: boolean;
};

export type ObstacleArray = {
  header?: { stamp: { sec: number; nanosec: number }; frame_id: string };
  obstacles?: TrackedObstacle[];
};

export type Power = {
  stamp?: { sec: number; nanosec: number };
  v_charge?: number;
  v_battery?: number;
  charge_current?: number;
  charger_enabled?: boolean;
  charger_status?: string;
};

export const enum StatusConstants {
  MOWER_STATUS_INITIALIZING = 0,
  MOWER_STATUS_OK = 255,
};

export type Status = {
  stamp?: { sec: number; nanosec: number };
  mower_status?: number;
  raspberry_pi_power?: boolean;
  is_charging?: boolean;
  esc_power?: boolean;
  rain_detected?: boolean;
  sound_module_available?: boolean;
  sound_module_busy?: boolean;
  ui_board_available?: boolean;
  mow_enabled?: boolean;
  mower_esc_status?: number;
  mower_esc_temperature?: number;
  mower_esc_current?: number;
  mower_motor_temperature?: number;
  mower_motor_rpm?: number;
};

export const enum TrackedObstacleConstants {
  TRANSIENT = 0,
  PERSISTENT = 1,
};

export type TrackedObstacle = {
  id?: number;
  polygon?: Polygon;
  centroid?: Point;
  radius?: number;
  first_seen?: { sec: number; nanosec: number };
  observation_count?: number;
  status?: number;
};

export const enum WheelTickConstants {
  WHEEL_VALID_FL = 1,
  WHEEL_VALID_FR = 2,
  WHEEL_VALID_RL = 4,
  WHEEL_VALID_RR = 8,
};

export type WheelTick = {
  stamp?: { sec: number; nanosec: number };
  wheel_tick_factor?: number;
  valid_wheels?: number;
  wheel_direction_fl?: number;
  wheel_ticks_fl?: number;
  wheel_direction_fr?: number;
  wheel_ticks_fr?: number;
  wheel_direction_rl?: number;
  wheel_ticks_rl?: number;
  wheel_direction_rr?: number;
  wheel_ticks_rr?: number;
};

// --- Additional types not from .msg files ---

export type Joy = {
  axes?: number[];
  buttons?: number[];
};

export type Map = {
  map_width?: number;
  map_height?: number;
  map_center_x?: number;
  map_center_y?: number;
  navigation_areas?: MapArea[];
  working_area?: MapArea[];
  dock_x?: number;
  dock_y?: number;
  dock_heading?: number;
};

export type DockingSensor = {
  dock_present?: boolean;
  dock_distance?: number;
};
