#!/usr/bin/env bash
# =============================================================================
# MowgliNext — One-line installer bootstrap
#
# This script is served at https://mowgli.garden/install.sh and accepts
# hardware configuration flags from the web composer so users can skip
# the interactive prompts for sensor selection.
#
# Usage (generated by the composer at mowgli.garden):
#   curl -sSL https://mowgli.garden/install.sh | bash -s -- \
#     --gps=ubx-uart --lidar=ldlidar-uart --tfluna=none
#
# Or run the fully interactive installer (no flags):
#   curl -sSL https://mowgli.garden/install.sh | bash
# =============================================================================

set -euo pipefail

# ── Colours ────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

info()  { echo -e "  ${GREEN}OK${NC}  $*"; }
warn()  { echo -e "  ${YELLOW}!!${NC}  $*"; }
error() { echo -e "${RED}[x]${NC} $*" >&2; }
step()  { echo -e "\n${CYAN}${BOLD}── $* ──${NC}"; }

repo_has_local_changes() {
  local repo_dir="${1:?repo_has_local_changes: missing repo dir}"
  [ -n "$(git -C "$repo_dir" status --porcelain --untracked-files=all 2>/dev/null || true)" ]
}

repo_current_branch() {
  local repo_dir="${1:?repo_current_branch: missing repo dir}"
  git -C "$repo_dir" symbolic-ref --quiet --short HEAD 2>/dev/null || printf 'detached\n'
}

update_existing_repo_checkout() {
  local repo_dir="${1:?update_existing_repo_checkout: missing repo dir}"
  local current_branch
  local local_head
  local remote_head

  info "Found existing git repository at $repo_dir"

  if repo_has_local_changes "$repo_dir"; then
    warn "Local changes detected in $repo_dir — skipping bootstrap git update."
    return 0
  fi

  current_branch="$(repo_current_branch "$repo_dir")"
  if [ "$current_branch" != "$REPO_BRANCH" ]; then
    warn "Repository is on '$current_branch'; bootstrap will not switch to '$REPO_BRANCH' automatically."
    return 0
  fi

  if ! git -C "$repo_dir" fetch --quiet origin "$REPO_BRANCH"; then
    warn "Could not fetch origin/$REPO_BRANCH — continuing with the current checkout."
    return 0
  fi

  if ! git -C "$repo_dir" rev-parse --verify "refs/remotes/origin/$REPO_BRANCH" >/dev/null 2>&1; then
    warn "Remote branch origin/$REPO_BRANCH is unavailable after fetch — continuing with the current checkout."
    return 0
  fi

  local_head="$(git -C "$repo_dir" rev-parse HEAD 2>/dev/null || true)"
  remote_head="$(git -C "$repo_dir" rev-parse "origin/$REPO_BRANCH" 2>/dev/null || true)"
  if [ -n "$local_head" ] && [ "$local_head" = "$remote_head" ]; then
    info "Existing installation is already up to date"
    return 0
  fi

  if git -C "$repo_dir" merge --ff-only "origin/$REPO_BRANCH" >/dev/null 2>&1; then
    info "Fast-forwarded existing installation to origin/$REPO_BRANCH"
    return 0
  fi

  warn "Existing checkout is not a clean fast-forward to origin/$REPO_BRANCH — continuing without updating."
}

# ── Defaults ───────────────────────────────────────────────────────────────
GNSS_FLAG=""
GPS_FLAG=""
LIDAR_FLAG=""
TFLUNA_FLAG=""
BACKEND_FLAG=""

REPO_URL="https://github.com/cedbossneo/mowglinext.git"
REPO_BRANCH="main"
INSTALL_DIR="${MOWGLI_HOME:-$HOME/mowglinext}"

# ── Parse flags ────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --backend=*) BACKEND_FLAG="${1#--backend=}"; shift ;;
    --gnss=*)    GNSS_FLAG="${1#--gnss=}"; shift ;;
    --gps=*)     GPS_FLAG="${1#--gps=}"; shift ;;
    --lidar=*)   LIDAR_FLAG="${1#--lidar=}"; shift ;;
    --tfluna=*)  TFLUNA_FLAG="${1#--tfluna=}"; shift ;;
    --branch=*)  REPO_BRANCH="${1#--branch=}"; shift ;;
    --help|-h)
      echo "Usage: curl -sSL https://mowgli.garden/install.sh | bash -s -- [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --backend=TYPE      Hardware backend: mowgli (default), mavros (advanced Pixhawk path)"
      echo "  --gnss=BACKEND     GNSS driver: gps (legacy UBX/NMEA), ublox (F9P), unicore (UM98x)"
      echo "  --gps=PRESET       GPS protocol+wiring: ubx-usb, ubx-uart, nmea-usb, nmea-uart"
      echo "                     (ignored by --gnss=unicore and --gnss=ublox)"
      echo "  --lidar=PRESET     LiDAR config: none, ldlidar-usb, ldlidar-uart,"
      echo "                     rplidar-usb, rplidar-uart, stl27l-usb, stl27l-uart"
      echo "  --tfluna=PRESET    Rangefinder: none, front, edge, both"
      echo "  --branch=BRANCH    Git branch (default: main)"
      echo ""
      echo "Without flags, the full interactive installer runs."
      exit 0
      ;;
    *)
      warn "Unknown option: $1"
      shift
      ;;
  esac
done

# ── Banner ─────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}"
echo '  __  __                  _ _ _  _  _           _   '
echo ' |  \/  | _____      __ | (_) \| || | _____  _| |_ '
echo ' | |\/| |/ _ \ \ /\ / / | | |  \  |/ _ \ \/ / __|'
echo ' | |  | | (_) \ V  V /  | | | |\  |  __/>  <| |_  '
echo ' |_|  |_|\___/ \_/\_/   |_|_|_| \_|\___/_/\_\\__|'
echo -e "${NC}"
echo -e "${DIM}  Open-source autonomous robot mower — mowgli.garden${NC}"
echo ""

# ── Prerequisite: git ──────────────────────────────────────────────────────
if ! command -v git &>/dev/null; then
  step "Installing git"
  if command -v apt-get &>/dev/null; then
    sudo apt-get update -qq && sudo apt-get install -y -qq git
  elif command -v dnf &>/dev/null; then
    sudo dnf install -y git
  else
    error "git is required but not found. Please install git first."
    exit 1
  fi
  info "git installed"
fi

# ── Clone / update repo ───────────────────────────────────────────────────
step "Preparing MowgliNext"

if [ -d "$INSTALL_DIR/.git" ]; then
  update_existing_repo_checkout "$INSTALL_DIR"
elif [ -d "$INSTALL_DIR" ]; then
  warn "$INSTALL_DIR exists but is not a git repo — backing up"
  mv "$INSTALL_DIR" "${INSTALL_DIR}.bak.$(date +%s)"
  git clone --branch "$REPO_BRANCH" --depth 1 "$REPO_URL" "$INSTALL_DIR"
  info "Cloned to $INSTALL_DIR"
else
  git clone --branch "$REPO_BRANCH" --depth 1 "$REPO_URL" "$INSTALL_DIR"
  info "Cloned to $INSTALL_DIR"
fi

# ── Write preset config if flags were provided ─────────────────────────────
PRESET_FILE="$INSTALL_DIR/install/.preset"
HAS_PRESET=false

if [[ -n "$BACKEND_FLAG" || -n "$GNSS_FLAG" || -n "$GPS_FLAG" || -n "$LIDAR_FLAG" || -n "$TFLUNA_FLAG" ]]; then
  HAS_PRESET=true
  step "Writing hardware preset from composer"

  cat > "$PRESET_FILE" <<PRESET
# Auto-generated by mowgli.garden install composer
# These values pre-fill the interactive installer prompts.
# The installer will skip questions for pre-configured sections.
PRESET

  # ── Hardware backend preset ────────────────────────────────────────────
  if [[ -n "$BACKEND_FLAG" ]]; then
    case "$BACKEND_FLAG" in
      mowgli|mavros)
        echo "HARDWARE_BACKEND=${BACKEND_FLAG}" >> "$PRESET_FILE"
        info "Hardware backend: $BACKEND_FLAG"
        ;;
      *)
        warn "Unknown hardware backend: $BACKEND_FLAG (expected mowgli|mavros) — will ask interactively"
        ;;
    esac
  fi

  # ── GNSS backend preset ────────────────────────────────────────────────
  if [[ -n "$GNSS_FLAG" ]]; then
    case "$GNSS_FLAG" in
      gps|ublox|unicore)
        echo "GNSS_BACKEND=${GNSS_FLAG}" >> "$PRESET_FILE"
        info "GNSS backend: $GNSS_FLAG"
        ;;
      *)
        warn "Unknown GNSS backend: $GNSS_FLAG (expected gps|ublox|unicore) — will ask interactively"
        ;;
    esac
  fi

  # ── GPS preset ─────────────────────────────────────────────────────────
  if [[ -n "$GPS_FLAG" && "${GNSS_FLAG:-}" != "ublox" ]]; then
    case "$GPS_FLAG" in
      ubx-usb)
        cat >> "$PRESET_FILE" <<'EOF'
GPS_CONNECTION=usb
GPS_PROTOCOL=UBX
GPS_PORT=/dev/gps
GPS_UART_DEVICE=
GPS_DEBUG_ENABLED=false
EOF
        ;;
      ubx-uart)
        cat >> "$PRESET_FILE" <<'EOF'
GPS_CONNECTION=uart
GPS_PROTOCOL=UBX
GPS_PORT=/dev/gps
GPS_UART_DEVICE=/dev/ttyAMA4
GPS_DEBUG_ENABLED=false
EOF
        ;;
      nmea-usb)
        cat >> "$PRESET_FILE" <<'EOF'
GPS_CONNECTION=usb
GPS_PROTOCOL=NMEA
GPS_PORT=/dev/gps
GPS_UART_DEVICE=
GPS_DEBUG_ENABLED=false
EOF
        ;;
      nmea-uart)
        cat >> "$PRESET_FILE" <<'EOF'
GPS_CONNECTION=uart
GPS_PROTOCOL=NMEA
GPS_PORT=/dev/gps
GPS_UART_DEVICE=/dev/ttyAMA4
GPS_DEBUG_ENABLED=false
EOF
        ;;
      *)
        warn "Unknown GPS preset: $GPS_FLAG — will ask interactively"
        ;;
    esac
    info "GPS: $GPS_FLAG"
  elif [[ -n "$GPS_FLAG" && "${GNSS_FLAG:-}" == "ublox" ]]; then
    info "GPS preset ignored for GNSS_BACKEND=ublox (u-blox USB-by-id runtime)"
  fi

  # ── LiDAR preset ──────────────────────────────────────────────────────
  if [[ -n "$LIDAR_FLAG" ]]; then
    case "$LIDAR_FLAG" in
      none)
        cat >> "$PRESET_FILE" <<'EOF'
LIDAR_ENABLED=false
LIDAR_TYPE=none
LIDAR_MODEL=
LIDAR_CONNECTION=
LIDAR_UART_DEVICE=
LIDAR_BAUD=0
EOF
        ;;
      ldlidar-usb)
        cat >> "$PRESET_FILE" <<'EOF'
LIDAR_ENABLED=true
LIDAR_TYPE=ldlidar
LIDAR_MODEL=LDLiDAR_LD19
LIDAR_CONNECTION=usb
LIDAR_PORT=/dev/lidar
LIDAR_UART_DEVICE=
LIDAR_BAUD=230400
EOF
        ;;
      ldlidar-uart)
        cat >> "$PRESET_FILE" <<'EOF'
LIDAR_ENABLED=true
LIDAR_TYPE=ldlidar
LIDAR_MODEL=LDLiDAR_LD19
LIDAR_CONNECTION=uart
LIDAR_PORT=/dev/lidar
LIDAR_UART_DEVICE=/dev/ttyAMA5
LIDAR_BAUD=230400
EOF
        ;;
      rplidar-usb)
        cat >> "$PRESET_FILE" <<'EOF'
LIDAR_ENABLED=true
LIDAR_TYPE=rplidar
LIDAR_MODEL=RPLIDAR_A1
LIDAR_CONNECTION=usb
LIDAR_PORT=/dev/lidar
LIDAR_UART_DEVICE=
LIDAR_BAUD=115200
EOF
        ;;
      rplidar-uart)
        cat >> "$PRESET_FILE" <<'EOF'
LIDAR_ENABLED=true
LIDAR_TYPE=rplidar
LIDAR_MODEL=RPLIDAR_A1
LIDAR_CONNECTION=uart
LIDAR_PORT=/dev/lidar
LIDAR_UART_DEVICE=/dev/ttyAMA5
LIDAR_BAUD=115200
EOF
        ;;
      stl27l-usb)
        cat >> "$PRESET_FILE" <<'EOF'
LIDAR_ENABLED=true
LIDAR_TYPE=stl27l
LIDAR_MODEL=STL27L
LIDAR_CONNECTION=usb
LIDAR_PORT=/dev/lidar
LIDAR_UART_DEVICE=
LIDAR_BAUD=230400
EOF
        ;;
      stl27l-uart)
        cat >> "$PRESET_FILE" <<'EOF'
LIDAR_ENABLED=true
LIDAR_TYPE=stl27l
LIDAR_MODEL=STL27L
LIDAR_CONNECTION=uart
LIDAR_PORT=/dev/lidar
LIDAR_UART_DEVICE=/dev/ttyAMA5
LIDAR_BAUD=230400
EOF
        ;;
      *)
        warn "Unknown LiDAR preset: $LIDAR_FLAG — will ask interactively"
        ;;
    esac
    info "LiDAR: $LIDAR_FLAG"
  fi

  # ── TF-Luna preset ────────────────────────────────────────────────────
  if [[ -n "$TFLUNA_FLAG" ]]; then
    case "$TFLUNA_FLAG" in
      none)
        cat >> "$PRESET_FILE" <<'EOF'
TFLUNA_FRONT_ENABLED=false
TFLUNA_EDGE_ENABLED=false
EOF
        ;;
      front)
        cat >> "$PRESET_FILE" <<'EOF'
TFLUNA_FRONT_ENABLED=true
TFLUNA_FRONT_PORT=/dev/tfluna_front
TFLUNA_FRONT_UART_DEVICE=/dev/ttyAMA3
TFLUNA_FRONT_BAUD=115200
TFLUNA_EDGE_ENABLED=false
EOF
        ;;
      edge)
        cat >> "$PRESET_FILE" <<'EOF'
TFLUNA_FRONT_ENABLED=false
TFLUNA_EDGE_ENABLED=true
TFLUNA_EDGE_PORT=/dev/tfluna_edge
TFLUNA_EDGE_UART_DEVICE=/dev/ttyAMA2
TFLUNA_EDGE_BAUD=115200
EOF
        ;;
      both)
        cat >> "$PRESET_FILE" <<'EOF'
TFLUNA_FRONT_ENABLED=true
TFLUNA_FRONT_PORT=/dev/tfluna_front
TFLUNA_FRONT_UART_DEVICE=/dev/ttyAMA3
TFLUNA_FRONT_BAUD=115200
TFLUNA_EDGE_ENABLED=true
TFLUNA_EDGE_PORT=/dev/tfluna_edge
TFLUNA_EDGE_UART_DEVICE=/dev/ttyAMA2
TFLUNA_EDGE_BAUD=115200
EOF
        ;;
      *)
        warn "Unknown TF-Luna preset: $TFLUNA_FLAG — will ask interactively"
        ;;
    esac
    info "Rangefinders: $TFLUNA_FLAG"
  fi

  echo ""
  info "Preset written to $PRESET_FILE"
  echo -e "${DIM}  The installer will use these values and skip sensor prompts.${NC}"
  echo -e "${DIM}  You'll still be asked for mower config (GPS datum, NTRIP, dock position).${NC}"
fi

# ── Hand off to the full installer ─────────────────────────────────────────
step "Launching installer"

INSTALLER="$INSTALL_DIR/install/mowglinext.sh"

if [ ! -f "$INSTALLER" ]; then
  error "Installer not found at $INSTALLER"
  error "The repository may be incomplete. Try deleting $INSTALL_DIR and running again."
  exit 1
fi

chmod +x "$INSTALLER"

# Forward the chosen channel to the installer so it skips the image-channel
# prompt and stays consistent with the branch we just cloned.
INSTALLER_ARGS=()
if [[ "$REPO_BRANCH" == "main" || "$REPO_BRANCH" == "dev" ]]; then
  INSTALLER_ARGS+=("--branch=$REPO_BRANCH")
fi

echo ""
if $HAS_PRESET; then
  info "Hardware sensors pre-configured — installer will skip those prompts."
else
  info "No hardware preset — running fully interactive installer."
fi
echo ""

# Reattach stdin to the controlling terminal — when invoked as
# `curl ... | bash`, stdin is the pipe and `read` prompts in the
# interactive installer would otherwise return immediately.
if [ -e /dev/tty ]; then
  exec bash "$INSTALLER" "${INSTALLER_ARGS[@]+"${INSTALLER_ARGS[@]}"}" </dev/tty
else
  warn "No /dev/tty available — interactive prompts may not work."
  exec bash "$INSTALLER" "${INSTALLER_ARGS[@]+"${INSTALLER_ARGS[@]}"}"
fi
