// Code generated by generate_go_msgs.sh — DO NOT EDIT.
package mowgli

import (
	"github.com/cedbossneo/mowglinext/pkg/msgs/geometry"
	"github.com/cedbossneo/mowglinext/pkg/msgs/nav"
)

// AddMowingAreaReq for mowgli_interfaces/srv/AddMowingArea request.
type AddMowingAreaReq struct {
	Area                      MapArea                        `json:"area"`
	IsNavigationArea          bool                           `json:"is_navigation_area"`
}

// AddMowingAreaRes for mowgli_interfaces/srv/AddMowingArea response.
type AddMowingAreaRes struct {
	Success                   bool                           `json:"success"`
}

// AreaRecordingReq for mowgli_interfaces/srv/AreaRecording request.
type AreaRecordingReq struct {
	Command                   uint8                          `json:"command"`
	AreaName                  string                         `json:"area_name"`
	IsExclusionZone           bool                           `json:"is_exclusion_zone"`
}

// AreaRecordingRes for mowgli_interfaces/srv/AreaRecording response.
type AreaRecordingRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
	Polygon                   geometry.Polygon               `json:"polygon"`
}

// CalibrateImuYawReq for mowgli_interfaces/srv/CalibrateImuYaw request.
type CalibrateImuYawReq struct {
	DurationSec               float64                        `json:"duration_sec"`
	MagOnly                   bool                           `json:"mag_only"`
}

// CalibrateImuYawRes for mowgli_interfaces/srv/CalibrateImuYaw response.
type CalibrateImuYawRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
	ImuYawRad                 float64                        `json:"imu_yaw_rad"`
	ImuYawDeg                 float64                        `json:"imu_yaw_deg"`
	SamplesUsed               int32                          `json:"samples_used"`
	StdDevDeg                 float64                        `json:"std_dev_deg"`
	ImuPitchRad               float64                        `json:"imu_pitch_rad"`
	ImuPitchDeg               float64                        `json:"imu_pitch_deg"`
	ImuRollRad                float64                        `json:"imu_roll_rad"`
	ImuRollDeg                float64                        `json:"imu_roll_deg"`
	StationarySamplesUsed     int32                          `json:"stationary_samples_used"`
	GravityMagMps2            float64                        `json:"gravity_mag_mps2"`
	DockValid                 bool                           `json:"dock_valid"`
	DockPoseX                 float64                        `json:"dock_pose_x"`
	DockPoseY                 float64                        `json:"dock_pose_y"`
	DockPoseYawRad            float64                        `json:"dock_pose_yaw_rad"`
	DockPoseYawDeg            float64                        `json:"dock_pose_yaw_deg"`
	DockYawSigmaDeg           float64                        `json:"dock_yaw_sigma_deg"`
	DockUndockDisplacementM   float64                        `json:"dock_undock_displacement_m"`
}

// ClearMapReq for mowgli_interfaces/srv/ClearMap request (empty).
type ClearMapReq struct{}

// ClearMapRes for mowgli_interfaces/srv/ClearMap response.
type ClearMapRes struct {
	Success                   bool                           `json:"success"`
}

// ClearObstacleReq for mowgli_interfaces/srv/ClearObstacle request.
type ClearObstacleReq struct {
	ObstacleId                uint32                         `json:"obstacle_id"`
}

// ClearObstacleRes for mowgli_interfaces/srv/ClearObstacle response.
type ClearObstacleRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

// EmergencyStopReq for mowgli_interfaces/srv/EmergencyStop request.
type EmergencyStopReq struct {
	Emergency                 uint8                          `json:"emergency"`
}

// EmergencyStopRes for mowgli_interfaces/srv/EmergencyStop response.
type EmergencyStopRes struct {
	Success                   bool                           `json:"success"`
}

// GetCoverageStatusReq for mowgli_interfaces/srv/GetCoverageStatus request.
type GetCoverageStatusReq struct {
	AreaIndex                 uint32                         `json:"area_index"`
}

// GetCoverageStatusRes for mowgli_interfaces/srv/GetCoverageStatus response.
type GetCoverageStatusRes struct {
	Success                   bool                           `json:"success"`
	CoveragePercent           float32                        `json:"coverage_percent"`
	TotalCells                uint32                         `json:"total_cells"`
	MowedCells                uint32                         `json:"mowed_cells"`
	ObstacleCells             uint32                         `json:"obstacle_cells"`
	StripsRemaining           uint32                         `json:"strips_remaining"`
}

// GetMowingAreaReq for mowgli_interfaces/srv/GetMowingArea request.
type GetMowingAreaReq struct {
	Index                     uint32                         `json:"index"`
}

// GetMowingAreaRes for mowgli_interfaces/srv/GetMowingArea response.
type GetMowingAreaRes struct {
	Area                      MapArea                        `json:"area"`
	Success                   bool                           `json:"success"`
}

// GetNextSegmentReq for mowgli_interfaces/srv/GetNextSegment request.
type GetNextSegmentReq struct {
	AreaIndex                 uint32                         `json:"area_index"`
	RobotX                    float64                        `json:"robot_x"`
	RobotY                    float64                        `json:"robot_y"`
	RobotYawRad               float64                        `json:"robot_yaw_rad"`
	PreferDirYawRad           float64                        `json:"prefer_dir_yaw_rad"`
	Boustrophedon             bool                           `json:"boustrophedon"`
	MaxSegmentLengthM         float64                        `json:"max_segment_length_m"`
}

// GetNextSegmentRes for mowgli_interfaces/srv/GetNextSegment response.
type GetNextSegmentRes struct {
	Success                   bool                           `json:"success"`
	CoverageComplete          bool                           `json:"coverage_complete"`
	SegmentPath               nav.Path                       `json:"segment_path"`
	TargetCellPose            geometry.PoseStamped           `json:"target_cell_pose"`
	IsLongTransit             bool                           `json:"is_long_transit"`
	CoveragePercent           float32                        `json:"coverage_percent"`
	SegmentsRemainingEstimate uint32                         `json:"segments_remaining_estimate"`
	DeadCellsCount            uint32                         `json:"dead_cells_count"`
	Phase                     string                         `json:"phase"`
	TerminationReason         string                         `json:"termination_reason"`
}

// GetNextStripReq for mowgli_interfaces/srv/GetNextStrip request.
type GetNextStripReq struct {
	AreaIndex                 uint32                         `json:"area_index"`
	RobotX                    float64                        `json:"robot_x"`
	RobotY                    float64                        `json:"robot_y"`
	PreferHeadland            bool                           `json:"prefer_headland"`
}

// GetNextStripRes for mowgli_interfaces/srv/GetNextStrip response.
type GetNextStripRes struct {
	Success                   bool                           `json:"success"`
	CoverageComplete          bool                           `json:"coverage_complete"`
	StripPath                 nav.Path                       `json:"strip_path"`
	TransitGoal               geometry.PoseStamped           `json:"transit_goal"`
	CoveragePercent           float32                        `json:"coverage_percent"`
	StripsRemaining           uint32                         `json:"strips_remaining"`
	Phase                     string                         `json:"phase"`
}

// GetRecoveryPointReq for mowgli_interfaces/srv/GetRecoveryPoint request (empty).
type GetRecoveryPointReq struct{}

// GetRecoveryPointRes for mowgli_interfaces/srv/GetRecoveryPoint response.
type GetRecoveryPointRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
	RecoveryPose              geometry.Pose                  `json:"recovery_pose"`
	DistanceOutside           float64                        `json:"distance_outside"`
}

// GetRemainingAreaPolygonReq for mowgli_interfaces/srv/GetRemainingAreaPolygon request.
type GetRemainingAreaPolygonReq struct {
	AreaId                    uint32                         `json:"area_id"`
}

// GetRemainingAreaPolygonRes for mowgli_interfaces/srv/GetRemainingAreaPolygon response.
type GetRemainingAreaPolygonRes struct {
	Success                   bool                           `json:"success"`
	Error                     string                         `json:"error"`
	Pieces                    []MapArea                      `json:"pieces"`
}

// HighLevelControlReq for mowgli_interfaces/srv/HighLevelControl request.
type HighLevelControlReq struct {
	Command                   uint8                          `json:"command"`
}

// HighLevelControlRes for mowgli_interfaces/srv/HighLevelControl response.
type HighLevelControlRes struct {
	Success                   bool                           `json:"success"`
}

// MarkSegmentBlockedReq for mowgli_interfaces/srv/MarkSegmentBlocked request.
type MarkSegmentBlockedReq struct {
	FailedPath                nav.Path                       `json:"failed_path"`
	AreaIndex                 uint32                         `json:"area_index"`
}

// MarkSegmentBlockedRes for mowgli_interfaces/srv/MarkSegmentBlocked response.
type MarkSegmentBlockedRes struct {
	Success                   bool                           `json:"success"`
	CellsMarkedBlocked        uint32                         `json:"cells_marked_blocked"`
	CellsPromotedDead         uint32                         `json:"cells_promoted_dead"`
}

// MowerControlReq for mowgli_interfaces/srv/MowerControl request.
type MowerControlReq struct {
	MowEnabled                uint8                          `json:"mow_enabled"`
	MowDirection              uint8                          `json:"mow_direction"`
}

// MowerControlRes for mowgli_interfaces/srv/MowerControl response.
type MowerControlRes struct {
	Success                   bool                           `json:"success"`
}

// PromoteObstacleReq for mowgli_interfaces/srv/PromoteObstacle request.
type PromoteObstacleReq struct {
	AreaIndex                 uint32                         `json:"area_index"`
	ObstacleId                uint32                         `json:"obstacle_id"`
	Polygon                   geometry.Polygon               `json:"polygon"`
}

// PromoteObstacleRes for mowgli_interfaces/srv/PromoteObstacle response.
type PromoteObstacleRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

// SetDockingPointReq for mowgli_interfaces/srv/SetDockingPoint request.
type SetDockingPointReq struct {
	DockingPose               geometry.Pose                  `json:"docking_pose"`
}

// SetDockingPointRes for mowgli_interfaces/srv/SetDockingPoint response.
type SetDockingPointRes struct {
	Success                   bool                           `json:"success"`
}

// StartInAreaReq for mowgli_interfaces/srv/StartInArea request.
type StartInAreaReq struct {
	Area                      uint8                          `json:"area"`
}

// StartInAreaRes for mowgli_interfaces/srv/StartInArea response.
type StartInAreaRes struct {
	Success                   bool                           `json:"success"`
}

// TriggerReplanReq for mowgli_interfaces/srv/TriggerReplan request.
type TriggerReplanReq struct {
	Reason                    string                         `json:"reason"`
}

// TriggerReplanRes for mowgli_interfaces/srv/TriggerReplan response.
type TriggerReplanRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

