// Code generated by generate_go_msgs.sh — DO NOT EDIT.
package mowgli

import (
	"github.com/cedbossneo/mowglinext/pkg/msgs/geometry"
	"github.com/cedbossneo/mowglinext/pkg/msgs/nav"
)

// AbsolutePose matches mowgli_interfaces/msg/AbsolutePose.
type AbsolutePose struct {
	Header                    geometry.Header                `json:"header"`
	SensorStamp               uint32                         `json:"sensor_stamp"`
	ReceivedStamp             uint32                         `json:"received_stamp"`
	Source                    uint8                          `json:"source"`
	Flags                     uint16                         `json:"flags"`
	OrientationValid          uint8                          `json:"orientation_valid"`
	MotionVectorValid         uint8                          `json:"motion_vector_valid"`
	PositionAccuracy          float32                        `json:"position_accuracy"`
	OrientationAccuracy       float32                        `json:"orientation_accuracy"`
	Pose                      geometry.PoseWithCovariance    `json:"pose"`
	MotionVector              geometry.Vector3               `json:"motion_vector"`
	VehicleHeading            float64                        `json:"vehicle_heading"`
	MotionHeading             float64                        `json:"motion_heading"`
}

// CoveragePath matches mowgli_interfaces/msg/CoveragePath.
type CoveragePath struct {
	IsOutline                 bool                           `json:"is_outline"`
	Path                      nav.Path                       `json:"path"`
}

// ESCStatus matches mowgli_interfaces/msg/ESCStatus.
type ESCStatus struct {
	Status                    uint8                          `json:"status"`
	Current                   float32                        `json:"current"`
	Tacho                     uint32                         `json:"tacho"`
	Rpm                       int16                          `json:"rpm"`
	TemperatureMotor          float32                        `json:"temperature_motor"`
	TemperaturePcb            float32                        `json:"temperature_pcb"`
}

// Emergency matches mowgli_interfaces/msg/Emergency.
type Emergency struct {
	Stamp                     geometry.Stamp                 `json:"stamp"`
	ActiveEmergency           bool                           `json:"active_emergency"`
	LatchedEmergency          bool                           `json:"latched_emergency"`
	LiftWarning               bool                           `json:"lift_warning"`
	LiftDurationSec           float32                        `json:"lift_duration_sec"`
	Reason                    string                         `json:"reason"`
}

// GnssStatus matches mowgli_interfaces/msg/GnssStatus.
type GnssStatus struct {
	Header                    geometry.Header                `json:"header"`
	FixType                   uint8                          `json:"fix_type"`
	HasFix                    bool                           `json:"has_fix"`
	DifferentialCorrections   bool                           `json:"differential_corrections"`
	CorrectionsActive         bool                           `json:"corrections_active"`
	DeadReckoning             bool                           `json:"dead_reckoning"`
	QualityPercent            float32                        `json:"quality_percent"`
	CapabilityFlags           uint32                         `json:"capability_flags"`
	PositionAccuracyM         float32                        `json:"position_accuracy_m"`
	HeadingDeg                float32                        `json:"heading_deg"`
	HeadingAccuracyDeg        float32                        `json:"heading_accuracy_deg"`
	SatellitesUsed            uint16                         `json:"satellites_used"`
	SatellitesVisible         uint16                         `json:"satellites_visible"`
	CorrectionAgeS            float32                        `json:"correction_age_s"`
}

// HighLevelStatus matches mowgli_interfaces/msg/HighLevelStatus.
type HighLevelStatus struct {
	State                     uint8                          `json:"state"`
	StateName                 string                         `json:"state_name"`
	SubStateName              string                         `json:"sub_state_name"`
	CurrentArea               int16                          `json:"current_area"`
	CurrentPath               int16                          `json:"current_path"`
	CurrentPathIndex          int16                          `json:"current_path_index"`
	TotalSwaths               int16                          `json:"total_swaths"`
	CompletedSwaths           int16                          `json:"completed_swaths"`
	SkippedSwaths             int16                          `json:"skipped_swaths"`
	GpsQualityPercent         float32                        `json:"gps_quality_percent"`
	BatteryPercent            float32                        `json:"battery_percent"`
	IsCharging                bool                           `json:"is_charging"`
	Emergency                 bool                           `json:"emergency"`
}

// ImuRaw matches mowgli_interfaces/msg/ImuRaw.
type ImuRaw struct {
	Dt                        uint16                         `json:"dt"`
	Ax                        float64                        `json:"ax"`
	Ay                        float64                        `json:"ay"`
	Az                        float64                        `json:"az"`
	Gx                        float64                        `json:"gx"`
	Gy                        float64                        `json:"gy"`
	Gz                        float64                        `json:"gz"`
	Mx                        float64                        `json:"mx"`
	My                        float64                        `json:"my"`
	Mz                        float64                        `json:"mz"`
}

// MapArea matches mowgli_interfaces/msg/MapArea.
type MapArea struct {
	Name                      string                         `json:"name"`
	Area                      geometry.Polygon               `json:"area"`
	Obstacles                 []geometry.Polygon             `json:"obstacles"`
	IsNavigationArea          bool                           `json:"is_navigation_area"`
}

// ObstacleArray matches mowgli_interfaces/msg/ObstacleArray.
type ObstacleArray struct {
	Header                    geometry.Header                `json:"header"`
	Obstacles                 []TrackedObstacle              `json:"obstacles"`
}

// Power matches mowgli_interfaces/msg/Power.
type Power struct {
	Stamp                     geometry.Stamp                 `json:"stamp"`
	VCharge                   float32                        `json:"v_charge"`
	VBattery                  float32                        `json:"v_battery"`
	ChargeCurrent             float32                        `json:"charge_current"`
	ChargerEnabled            bool                           `json:"charger_enabled"`
	ChargerStatus             string                         `json:"charger_status"`
}

// Status matches mowgli_interfaces/msg/Status.
type Status struct {
	Stamp                     geometry.Stamp                 `json:"stamp"`
	MowerStatus               uint8                          `json:"mower_status"`
	RaspberryPiPower          bool                           `json:"raspberry_pi_power"`
	IsCharging                bool                           `json:"is_charging"`
	EscPower                  bool                           `json:"esc_power"`
	RainDetected              bool                           `json:"rain_detected"`
	SoundModuleAvailable      bool                           `json:"sound_module_available"`
	SoundModuleBusy           bool                           `json:"sound_module_busy"`
	UiBoardAvailable          bool                           `json:"ui_board_available"`
	MowEnabled                bool                           `json:"mow_enabled"`
	MowerEscStatus            uint8                          `json:"mower_esc_status"`
	MowerEscTemperature       float32                        `json:"mower_esc_temperature"`
	MowerEscCurrent           float32                        `json:"mower_esc_current"`
	MowerMotorTemperature     float32                        `json:"mower_motor_temperature"`
	MowerMotorRpm             float32                        `json:"mower_motor_rpm"`
}

// TrackedObstacle matches mowgli_interfaces/msg/TrackedObstacle.
type TrackedObstacle struct {
	Id                        uint32                         `json:"id"`
	Polygon                   geometry.Polygon               `json:"polygon"`
	Centroid                  geometry.Point                 `json:"centroid"`
	Radius                    float64                        `json:"radius"`
	FirstSeen                 geometry.Stamp                 `json:"first_seen"`
	ObservationCount          uint32                         `json:"observation_count"`
	Status                    uint8                          `json:"status"`
}

// WheelTick matches mowgli_interfaces/msg/WheelTick.
type WheelTick struct {
	Stamp                     geometry.Stamp                 `json:"stamp"`
	WheelTickFactor           uint32                         `json:"wheel_tick_factor"`
	ValidWheels               uint8                          `json:"valid_wheels"`
	WheelDirectionFl          uint8                          `json:"wheel_direction_fl"`
	WheelTicksFl              uint32                         `json:"wheel_ticks_fl"`
	WheelDirectionFr          uint8                          `json:"wheel_direction_fr"`
	WheelTicksFr              uint32                         `json:"wheel_ticks_fr"`
	WheelDirectionRl          uint8                          `json:"wheel_direction_rl"`
	WheelTicksRl              uint32                         `json:"wheel_ticks_rl"`
	WheelDirectionRr          uint8                          `json:"wheel_direction_rr"`
	WheelTicksRr              uint32                         `json:"wheel_ticks_rr"`
}

